spring:
  application:
    name: dataset-manager-service
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      generatorService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        registerHealthIndicator: true
  timelimiter:
    instances:
      generatorService:
        timeoutDuration: 5s