spring.application.name=dataset-manager-service
server.port=8081
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:mem:myH2Database
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.cache=false


# Base H2 persistante sur disque
#spring.datasource.url=jdbc:h2:file:./data/myH2Database;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
#spring.datasource.driverClassName=org.h2.Driver


# Optionnel : pour accéder à la console H2
# http://localhost:8081/h2-console